import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.Clock.system;
import static java.time.InstantSource.system;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class Update extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst,pst1;
    ResultSet rs;
    /**
     * Creates new form ViewProfile
     */
 
    String k;
    
    Update(String v) {
        k=v;
                initComponents();
                
                email_in.setText(k);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection  con = DriverManager.getConnection("jdbc:mysql://localhost/personalinformaation_javadb","root","");
           String sql=("SELECT Name from registration where Email='"+k+"';");
            PreparedStatement pst=con.prepareStatement(sql);
            String j;
            ResultSet rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                name_in.setText(j); 
                name_in.setEditable(false);
                }
           sql=("SELECT Mobile_Number from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                mobilenumber_in.setText(j); 
                mobilenumber_in.setEditable(false);
                }
           sql=("SELECT Gender from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                gender_in.setText(j); 
                gender_in.setEditable(false);
                }
                sql=("SELECT City from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                city_in.setText(j); 
                city_in.setEditable(false);
                }
                sql=("SELECT Date_of_Birth from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                date_in.setText(j); 
                date_in.setEditable(false);
                }
                sql=("SELECT Password from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                password_in.setText(j); 
                confirmpassword_in.setEditable(false);
                }
                
                 sql=("SELECT Age from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                age_in.setText(j); 
                }
                
                sql=("SELECT Confirm_Password from registration where Email='"+k+"';");
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
                if(rs.next()){
                j=rs.getString(1);
                confirmpassword_in.setText(j); 
                confirmpassword_in.setEditable(false);
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Database Exception Error..."+e);
            }
        
    }

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        city_in = new javax.swing.JTextField();
        name_in = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        email_in = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        mobilenumber_in = new javax.swing.JTextField();
        date_in = new javax.swing.JTextField();
        age_in = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password_in = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        confirmpassword_in = new javax.swing.JPasswordField();
        gender_in = new javax.swing.JTextField();
        editname = new javax.swing.JButton();
        editemail = new javax.swing.JButton();
        editmob = new javax.swing.JButton();
        editgen = new javax.swing.JButton();
        editdob = new javax.swing.JButton();
        editage = new javax.swing.JButton();
        editcity = new javax.swing.JButton();
        editpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("   UPDATE  PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("City");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Confirm Password");

        city_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_inActionPerformed(evt);
            }
        });

        name_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        email_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_inActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 15)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        age_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_inActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date of Birth");

        password_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_inActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Age");

        confirmpassword_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpassword_inActionPerformed(evt);
            }
        });

        editname.setText("edit");
        editname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editnameMouseClicked(evt);
            }
        });
        editname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editnameActionPerformed(evt);
            }
        });

        editemail.setText("edit");
        editemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editemailMouseClicked(evt);
            }
        });

        editmob.setText("edit");
        editmob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editmobMouseClicked(evt);
            }
        });

        editgen.setText("edit");
        editgen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editgenMouseClicked(evt);
            }
        });

        editdob.setText("edit");
        editdob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editdobMouseClicked(evt);
            }
        });

        editage.setText("edit");
        editage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editageMouseClicked(evt);
            }
        });
        editage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editageActionPerformed(evt);
            }
        });

        editcity.setText("edit");
        editcity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editcityMouseClicked(evt);
            }
        });
        editcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcityActionPerformed(evt);
            }
        });

        editpass.setText("edit");
        editpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editpassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmpassword_in, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gender_in, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(date_in, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(age_in, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(city_in, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_in, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(editcity)
                                .addComponent(editage)
                                .addComponent(editdob)
                                .addComponent(editgen)
                                .addComponent(editemail)
                                .addComponent(editname)
                                .addComponent(editmob))
                            .addComponent(editpass))))
                .addGap(56, 56, 56))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addComponent(jLabel6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel4)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(mobilenumber_in, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(email_in, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(name_in, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(jButton2)))))
                    .addContainerGap(171, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editname)
                .addGap(32, 32, 32)
                .addComponent(editemail)
                .addGap(28, 28, 28)
                .addComponent(editmob)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editgen))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editdob)
                    .addComponent(date_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editage)
                    .addComponent(age_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editcity)
                    .addComponent(city_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editpass)
                    .addComponent(password_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(confirmpassword_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(name_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(email_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(mobilenumber_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addComponent(jLabel5)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel6)
                    .addGap(32, 32, 32)
                    .addComponent(jLabel7)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel10)
                    .addGap(34, 34, 34)
                    .addComponent(jLabel8)
                    .addGap(39, 39, 39)
                    .addComponent(jLabel9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void city_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_inActionPerformed

    private void name_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void email_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_inActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Dashboard r1=new Dashboard(k);
                 r1.setVisible(true);
                 dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void password_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_inActionPerformed

    private void confirmpassword_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpassword_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmpassword_inActionPerformed

    private void age_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_inActionPerformed

    private void editageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editageActionPerformed

    private void editnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editnameActionPerformed

    private void editnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editnameMouseClicked
        // TODO add your handling code here:
        name_in.setText("");
        name_in.grabFocus();
        name_in.setEditable(true);
    }//GEN-LAST:event_editnameMouseClicked

    private void editemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editemailMouseClicked
        // TODO add your handling code here:
        email_in.setText("");
        email_in.grabFocus();
        email_in.setEditable(true);
    }//GEN-LAST:event_editemailMouseClicked

    private void editmobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobMouseClicked
        // TODO add your handling code here:
        mobilenumber_in.setText("");
        mobilenumber_in.grabFocus();
        mobilenumber_in.setEditable(true);
    }//GEN-LAST:event_editmobMouseClicked

    private void editgenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editgenMouseClicked
        // TODO add your handling code here:
        gender_in.setText("");
        gender_in.grabFocus();
        gender_in.setEditable(true);
    }//GEN-LAST:event_editgenMouseClicked

    private void editdobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editdobMouseClicked
        // TODO add your handling code here:
        date_in.setText("");
        date_in.grabFocus();
        date_in.setEditable(true);
    }//GEN-LAST:event_editdobMouseClicked

    private void editageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editageMouseClicked
        // TODO add your handling code here:
        age_in.setText("");
        age_in.grabFocus();
        age_in.setEditable(true);
    }//GEN-LAST:event_editageMouseClicked

    private void editcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editcityActionPerformed

    private void editcityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editcityMouseClicked
        // TODO add your handling code here:
        city_in.setText("");
        city_in.grabFocus();
        city_in.setEditable(true);
    }//GEN-LAST:event_editcityMouseClicked

    private void editpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editpassMouseClicked
        // TODO add your handling code here:
        password_in.setText("");
        password_in.grabFocus();
        password_in.setEditable(true);
        confirmpassword_in.setText("");
        confirmpassword_in.setEditable(true);
    }//GEN-LAST:event_editpassMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String name=name_in.getText();
        String email=email_in.getText();
        String mobilenumber=mobilenumber_in.getText();
        String gender=gender_in.getText();
        String date=date_in.getText();
        String age1 = age_in.getText();
        String city=city_in.getText();
        String pass=password_in.getText();
        String confirmpass=confirmpassword_in.getText();
        
        if(email.trim().equals("") || pass.trim().equals("") || name.trim().equals("") || 
                date.trim().equals("") || mobilenumber.trim().equals("") || gender.trim().equals("")|| city.trim().equals("") 
                || age1.trim().equals("") || confirmpass.trim().equals("") ){
            JOptionPane.showMessageDialog(null,"All Fields are Compulsory");
        }
        else{
            try{
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost/personalinformaation_javadb","root","");
             String sql="Set foreign_key_checks=0";
              pst=con.prepareStatement(sql);
              pst.executeUpdate();
             sql="UPDATE registration SET Name=?,Email=?,Mobile_Number=?,Gender=?,Date_of_Birth=?,Age=?,City=?,Password=?,Confirm_Password=? where Email='"+k+"';";

                pst=con.prepareStatement(sql);
                pst.setString(1,name);
                pst.setString(2,email);
                pst.setString(3,mobilenumber);
                pst.setString(4,gender);
                pst.setString(5,date);
                pst.setString(6,age1);
                pst.setString(7,city);
                pst.setString(8,pass);
                pst.setString(9,confirmpass);
                pst.executeUpdate();
                
                
                sql="UPDATE loginpage SET Email=?,Password=? where Email='"+k+"';";

                pst=con.prepareStatement(sql);
                pst.setString(1,email);
                pst.setString(2,pass);
                pst.executeUpdate();
                sql="Set foreign_key_checks=1";
              pst=con.prepareStatement(sql);
              pst.executeUpdate();
                k=email;
                JOptionPane.showMessageDialog(null,"Sucessfully Updated...");
                Dashboard r1=new Dashboard(k);
                 r1.setVisible(true);
                 dispose();
                

    }//GEN-LAST:event_jButton1MouseClicked
catch(Exception e){
                JOptionPane.showMessageDialog(null,"Database Exception Error..."+e);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_in;
    private javax.swing.JTextField city_in;
    private javax.swing.JPasswordField confirmpassword_in;
    private javax.swing.JTextField date_in;
    private javax.swing.JButton editage;
    private javax.swing.JButton editcity;
    private javax.swing.JButton editdob;
    private javax.swing.JButton editemail;
    private javax.swing.JButton editgen;
    private javax.swing.JButton editmob;
    private javax.swing.JButton editname;
    private javax.swing.JButton editpass;
    private javax.swing.JTextField email_in;
    private javax.swing.JTextField gender_in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mobilenumber_in;
    private javax.swing.JTextField name_in;
    private javax.swing.JPasswordField password_in;
    // End of variables declaration//GEN-END:variables
}
